reichlab/covid19-forecast-hub

data-processed/UT-Mobility/metadata-UT-Mobility.txt

@nickreich This is second try at updating our forecast for 2020-05-25 (see #375)
I know there's a conflict with the metadata, but I only updated it to reflect changes to our model. The current version of our metadata on the main repo should be replaced as it is not up to date anymore.

Forecast with new model as of 2020-05-25 (2nd attempt)

---

.travis.yml

This is a test PR to bump up the node version to `10.2`. I have been personally using this version for local builds and deployment and it works fine. hence, it should also be updated here.

Update node to 10.2

---

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py
visualization/requirements.txt

Use `model_abbr` instead of `model_name` for model identification when uploading to zoltar. 
Related PR in zoltpy: https://github.com/reichlab/zoltpy/pull/36

Use model_abbr instead of model_name for model identification

---

data-truth/zoltar-truth-data.py

- Update the Zoltar truth script to use a longer horizon (max of 20 wk ahead instead of the previous max of 4 wk ahead)

Update wk-ahead from 4 to 20 in zoltar truth data creation

---

visualization/scripts/convert_forecasts.py
visualization/scripts/parse-data.js

Include only those models in visualization that have inc/cum targets in their forecasts. 
- After converting forecasts (`convert_forecast.py`), add a check to see if the _filtered_ DataFrame has at least one row, otherwise, delete the file. 
- Then parse through all models in all targets and remove folders that have no forecast files. 
Closes #1234

Include only models that have inc/cum targets

---

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py

Resolve issue [1417](https://github.com/reichlab/covid19-forecast-hub/issues/1417) due to changes in zoltpy breaking zoltar integration

Resolve issue-1417

---

.github/workflows/update_truth_weekly.yml
data-truth/nytimes/nytimes.py
data-truth/usafacts/usafacts.py
travis/update_truth_weekly.sh

- Add data-truth/nytimes/nytimes.py script that performs what nytimes.R does
- Add data-truth/usafacts/usafacts.py script that performs what usafacts.R does
- Add travis/update_truth_weekly.sh script that is based off update-truth.sh, adding the command for running the 2 aforementioned script, uploading to truth to zoltar and pushing to github
- Add .github/workflows/update_truth_weekly.yml to create a workflow scheduled at 12pm every sunday 
- Testing: 
- The csv files produced by the two python scripts are compared against the files created by the R script. The contents are identical
Closes #338

Codes to update truth weekly

---

travis/vis-build.sh
visualization/scripts/parse-data.js

- Recent builds on Github Actions are failing because the visualization build was copying the _entire_ `data-processed` folder (~ 7GB) inside the `visualization/data` folder and then processing each forecast CSV file to be added to the viz. Hence, the copy was doubling the size of the repository on the CI Build machine which was causing it to run out of memory. 
- Since the CI does not really use the CSV in the `data-processed` folder, we can move the CSV files to the `data` folder instead of copying. This is the least destructive way I saw to fix the memory issue. 
- We don't want this to happen on our local machines. So added this change for only the case when we run it from Github Actions. 
- When committing the local visualization back, we were adding _all_ unchanged files back. …

Fix memory issue while building local visualization on Github Actions

---

travis/vis-build.sh
visualization/scripts/parse-data.js

Reverts reichlab/covid19-forecast-hub#1856
Some parts of the build code does require data to still be in the data-processed folder, so we may need to fix that before making this change.

Revert "Fix memory issue while building local visualization on Github Actions"

---

data-truth/zoltar-truth-data.py

This change fixes the addition of invalid Zoltar truth targets to `zoltar-truth.csv`.
In the screenshot below, you can see that the old truth data was adding `20 wk ahead` targets for timezeros in the future as well. This was because it was doing a merge with only the MMRWeek column instead of the combination of (MMRweek, MMRYear). This change fixes this problem as you see in the screenshot.

Fix invalid targets being added to the zoltar truth data

---

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py

This fixes the error in the Zoltar upload job. A nice explanation of the error is present in #1984 . 
This can be fixed if we handle the `RuntimeError`. This is how the flow goes: 
- If a `RuntimeError` occurs when `upload_forecast` is called, first check if this error was indeed caused due to an existing forecast was present. Any [such error ](https://github.com/reichlab/covid19-forecast-hub/runs/1385007918?check_suite_focus=true#step:7:2194)text starts with `A forecast already exists..` and the HTTP response code is `400`. Hence, check for this. 
- If true, then delete that forecast on Zoltar using the `zoltpy` util method. 
- Retry the upload of the forecast. 
**PS:** Before this PR is merged, the corresponding zoltpy PR should be merged: https://github.com/reichlab/zoltpy/pull/46

Handle error when forecast is present on zoltar

---

visualization/vis-master/scripts/parse-season.js

Remove the first 5 weeks since there are no data and extend to 16 weeks next season in the x-axis
#1669

Viz: remove the first 5 weeks and extend to 16 weeks in next season

---

data-truth/nytimes/nytimes.py

With the previous fix for the NYTimes truth data, the `fips` field used to be reformatted to truncate the zeros in the left, if present. This used to throw errors in when used in R. This is the fix for retaining the zeros in the `fips` field. This is done by treating the `fips` field as a string in pandas.

Update nytimes script to handle fips code reformatting

---

data-processed/AIpert-pwllnod/metadata-AIpert-pwllnod.txt

The `website_url` field had 2 URLs; one was the Github link and the other to the website. The Github URL goes in the `repo_url` section of the metadata instead of `website_url`. Fixing this manually for the metadata file. 
This change is required because builds in the static site generation fail due to improperly formatted URL in the `website_url` field in Zoltar.

Update metadata file to adhere to schema

---

.github/workflows/upload_to_zoltar.yml

- Add logs in the Zoltar script to check for free space. This will help using estimating/tracking the free space available.  
- Also added another log to heck for free space after checking out the repository.

Add logs to check for free space on zoltar upload build

---

.github/workflows/active_update_truth_weekly.yml
.github/workflows/deprecated_update_truth_weekly.yml
.github/workflows/upload_to_zoltar.yml

Use the market place maximize-build-space github action to free up ~40 GBs of space on GH action virtual environment. Closes #3244 
---
- Team name: 
- Model Name: 
---
- Team name: 
---

Use maximize-build-space for GH action

---

.github/workflows/active_update_truth_weekly.yml

An un-used step in the Truth Upload is causing error. Removing it since it's not needed.
---
- Team name: 
- Model Name: 
---
- Team name: 
---

Remove unneeded storage saving step

---

code/reports/plot-hospitalizations.R

Zoomed-in figures automatically adjust to the latest forecasts (shows a two-month window, one month before and one month after the most recent Tuesday forecast and the y limits automatically adjust to ensure no point forecasts or quantiles are cut off)

updates to plot-hospitalizations.R

---

.github/workflows/active_update_truth_weekly.yml
code/R_scripts/generate_truth_csvs.R

(Note) Keep "USAFact" in the workflow name for simple organizations in GitHub action, but it is not generating USAFact truth data anymore.

Turn off USAFact truth generation in workflow

---

code/reports/render_reports.R

Found a bug while developing Amazon VM script.

replaced undefined `curr_state` variable in error print

---

code/reports/render_reports.R

@Martha and I cleaned up the file: removed commented-out code, added a check for required ensemble files, and added `quit()` calls with appropriate unix error codes.

cleaned up render_reports.R to quit() using unix error codes so scripts can call and check for success

---

.github/CODE_OF_CONDUCT.md

A code of conduct is required for participation in Netlify's open source program. This is the same one we discussed and adopted for the Hubverse. The only difference is the reporting contact list.

Add a code of conduct for the forecast hub
