reichlab/covid19-forecast-hub

template/2020-04-13-TeamName-ModelName.csv
I added the csv to the directory `template\` let me know if this is okay or if I should rename/change anything!
=> Add an example `csv`

README.md
Made definition of "value" more precise (requires evaluation of quantile function rather than cumulative distribution function) and made some other very minor corrections.
May also consider clarifying that from Tue onwards week-ahead forecasts are for following week.
=> Minor corrections in README.md 

data-processed/explore_processed_data.R, data-processed/read_processed_data.R
This also handles NAs more properly.
=> Update data-processed/ shiny app to associate warnings to files

data-processed/explore_processed_data.R
the variable was character, but was assumed to be numeric.
now it is explicitly turned into numeric
fixes #91
=> Calculate max forecast accurately

data-processed/IowaStateLW-STEM10/2020-04-26-IowaStateLW-STEM10.csv, data-processed/IowaStateLW-STEM15/2020-04-26-IowaStateLW-STEM15.csv
Received data via email on 2020-04-30
This should just use the daily targets with Saturday target_end_date to compute weekly targets
=> Compute weekly targets from daily targets for IowaStateLW

data-processed/UCLAML-SuEIR/metadata-UCLAML-SuEIR.txt
add SuEIR model csv/meta files (fix location issue)
=> add SuEIR model csv/meta files (fix location issue) 

code/validation/functions_plausibility.R
Looks like verify_no_na() is not returning TRUE when it is supposed to
=> Make validate_file return all true when all checks pass

data-processed/UCLA-SuEIR/metadata-UCLA-SuEIR.txt
Update UCLA-SuEIR meta file this_model_is_unconditional to FALSE
=> Update meta file for more accurate description

code/validation/locally_validated_files.csv
update UCLA-SuEIR model (05-17)
=> update UCLA-SuEIR model (05-17)

data-raw/UA-EpiCovDA/LICENSE.txt, data-raw/UA-EpiCovDA/metadata-UA-EpiCovDA.txt
Submit first forecasts for EpiCovDA model
=> UA-EpiCovDA Forecasts

data-processed/UA-EpiCovDA/LICENSE.txt, data-processed/UA-EpiCovDA/metadata-UA-EpiCovDA.txt
Add forecasts to correct folder (data-processed) and fix FIPS code issues
=> Submission for UA-EpiCovDA (correct folder) + fix FIPS issue

data-processed/MIT_CovidAnalytics-DELPHI/metadata-MIT_CovidAnalytics-DELPHI.txt
Updated METADATA for methodology update, and added new predictions
=> MIT Update 0525

data-processed/COVID19SimCons-COVID19Sim/LICENSE-COVID19SimCons.txt
CC Non-commercial license file has been added.
=> added license file

data-processed/IowaStateLW-STEM/metadata-IowaStateLW-STEM.txt
We realized that we didn't include the model assumptions for generating projections. The projections assume that the data used is reliable, the future will continue to follow the current pattern, and current interventions will remain the same until the end of the forecasting period. So we added one sentence in the metadata file. Thank you.
=> Latest projection results and updated metadata.

data-processed/PSI-DRAFT/metadata-PSI-DRAFT.txt
=> PSI EW21 forecast submission

code/validation/test-formatting.py
- Separate out the data error reporting from metadata errors as per #395 .
=> Separate out metadata errors from data errors.

data-processed/CDDEP-GlobalAgentBasedModel/2020-06-01-CDDEP-GlobalAgentBasedModel.csv, data-processed/CDDEP-GlobalAgentBasedModel/metadata-CDDEP-GlobalAgentBasedModel.txt
=> Add CDDEP model output

data-processed/UCLA-SuEIR/metadata-UCLA-SuEIR.txt
update SuEIR forecast for some states/ update meta files
=> update SuEIR forecast for some states/ update meta files

data-processed/PSI-DRAFT/LICENSE-PSI.txt
- weekly forecast submission
- add License file
=> PSI EW22 Submission

README.md
- update PSI link and license in README.md
=> Update PSI info in README.md

data-processed/Geneva-DeterministicGrowth/2020-06-14-Geneva-DeterministicGrowth.csv
Model change - need to discuss change to 'deterministic growth' model name change.
=> Adding 14/06 update

data-processed/NotreDame-mobility/metadata-NotreDame-mobility.txt
This is a new, simpler, model by the Notre Dame team, including the whole US
=> First forecast for ND mobility model

data-processed/Geneva-DetGrowth/2020-06-21-Geneva-DetGrowth.csv
Adding new updates with new metadata from the new set up. Renamed to DetGrowth.
=> Adding 21/6 Geneva/SDSC DetGrowth

data-processed/PSI-DRAFT/metadata-PSI-DRAFT.txt
- EW24 forecast submission
- Also includes some updates to the metadata.txt file
- Additional note: I am unable to run the test-formatting.py script after its update this week.  After adding the 'pykwalify' package, it crashes with the following error:
```    
Traceback (most recent call last):
File "code/validation/test-formatting.py", line 191, in <module>
main()
File "code/validation/test-formatting.py", line 187, in main
check_formatting(my_path)
File "code/validation/test-formatting.py", line 123, in check_formatting
is_metadata_error, metadata_error_output = check_for_metadata(path, cache= metadata_validation_cache)
File "/Users/turtle/GitReps/covid19-forecast-hub/code/validation/validation_functions/metadata.py", line 140, in check_for_metadata
is_metadata_error, …
```
=> PSI EW24 forecast-update

data-processed/MIT_CovidAnalytics-DELPHI/metadata-MIT_CovidAnalytics-DELPHI.txt
Please include a brief description of your change.
=> MIT 0622 Update

data-processed/MIT_CovAlliance-SIR/metadata-MIT_CovAlliance-SIR.txt
Changing contact email address for one contributor. Please update this email address for the Google Group! Also hoping for clarification on the CDC update schedule in this issue #628. Thank you!
=> MITCovAlliance: Changing contact email address

data-processed/Geneva-DetGrowth/2020-06-28-Geneva-DetGrowth.csv
=> Adding 28/06 Geneva-DetGrowth update

data-processed/UCLA-SuEIR/metadata-UCLA-SuEIR.txt
prediction update for UCLA-SuEIR model/ add hospitalization projections
prediction update for UCLA-SuEIR model/ add hospitalization projections
---
- Team name: UCLA
- Model name that is being updated:  SuEIR
---
=> prediction update for UCLA-SuEIR model/ add hospitalization projections

code/validation/locally_validated_files.csv, code/validation/validated_files.csv
Updated predictions from auquan made as of 28 June
=> updated predictions from auquan for 28 june

data-processed/COVIDhub-baseline/metadata-COVIDhub-baseline.txt
- Team name: COVIDhub
- Model Name: baseline
- Institution:  UMass
=> COVIDhub-baseline

.gitattributes
File contains:
1 - 20 wk ahead cum death (US and state level, with 23 quantiles),
1 - 20 wk ahead inc death (US and state level, with 23 quantiles),
1 - 8 wk ahead inc case (US, state and county level, with 7 quantiles). 
We had to remove the county-level results for cum/inc death due to file size when uploading. 
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Forecast IowaStateLW-STEM 0705

data-processed/UM_CFG-RidgeTfReg/metadata-UM_CFG-RidgeTfReg.txt
Added email addresses to metadata file
- [ x] Specify a proper PR title with your team name.
- [ x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).
=> UM_CFG Added Emails to Metadata

README.md
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Add missing license info for epiforecasts

README.md
Add UM to list of collaborators
---
=> Add University of Michigan to list of collaborators 

data-locations/locations.csv
Add county to county names
---
---
=> add "County" to county names

data-processed/COVIDhub-baseline/metadata-COVIDhub-baseline.txt
- Team name: COVIDhub
- Model name that is being updated:  baseline
=> 2020-07-13-COVIDhub-baseline and revision to meta data

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD-CovidSP forecast update 7/13/2020

.github/workflows/upload_to_zoltar.yml
Covid19Sim -  Simulator
Adding new forecast
=> Covid19sim - Simulator -Adding new forecast 

README.md
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> add USACE website link

data-processed/RPI-UW-Mob-Collision/metadata-RPI-UW-Mob-Collision.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Updated metafile

data-processed/GT_CHHS-COVID19/metadata-GT_CHHS-COVID19.txt
=> Updated metadata file GT_CHHS

data-processed/CEID-Walk/metadata-CEID-Walk.txt
First submission of primary model for new team.
---
- Team name: CEID
- Model Name: Walk
- Institution:  University of Georgia Center for the Ecology of Infectious Diseases
---
- [ X] Specify a proper PR title with your team name.
=> New team and model, team CEID and model Walk, forecast from 2020-08-09

data-truth/zoltar-truth-data.py
Reverts reichlab/covid19-forecast-hub#1092
=> Revert "Update wk-ahead from 4 to 20 in zoltar truth data creation"

data-processed/contacts.txt
assigned Estee to contact for google team
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Add Google Cloud team

data-processed/CEID-Walk/metadata-CEID-Walk.txt
We are **adding new forecasts** to an existing model. The details are:
- Team name: University of Georgia Center for the Ecology of Infectious Diseases Forecasting Working Group (CEID)
- Model name that is being updated:  Walk
---
=> Add new forecast for Walk model of team CEID.

data-processed/contacts.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Update contacts (TTU)

data-processed/contacts.txt
=> add new team to contacts

README.md
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> add new team iqvia

data-processed/WalmartLabsML-LogForecasting/metadata-WalmartLabsML-LogForecasting.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Adding metadata file and directory

data-processed/SteveMcConnell-CovidComplete/metadata-SteveMcConnell-CovidComplete.txt
Updated Metadata Description to clarify timeframes forecast by the model.
=> Steve McConnell-CovidComplete - Updated Metadata Description

data-processed/WalmartLabsML-LogForecasting/metadata-WalmartLabsML-LogForecasting.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Updated info

data-processed/CU-scenario_high/metadata-CU-scenario_high.txt, data-processed/CU-scenario_mid/metadata-CU-scenario_mid.txt
---
- Team name: CU
- Model name that is being updated:  all
---
=> CU 8-23: NOTE- change in scenarios

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py
This PR is to resolve this [issue](https://github.com/reichlab/covid19-forecast-hub/issues/1244). The current use of zoltpy's util.upload_forecast() method is slow, since it polls the list of all projects, and the list of all model in a project every time this method is called to find the model it needs to upload the forecast to. We can improve this by passing the reference of that model directly to the upload method and remove this polling step. This change is reflected in a new, custom method of uploading that is for this script use only
---
=> Add new upload method to speed up uploading to zoltar

data-processed/IBF-TimeSeries/2020-09-07-IBF-TimeSeries.csv, data-processed/IBF-TimeSeries/metadata-IBF-TimeSeries.txt
First time submitting Metadata and forecast data
---
- Team name: Institute of Business Forecasting
- Model Name: Time Series
- Institution:  IBF
---
=> IBF-TimeSeries 09/07/2020 Submission

data-truth/Dates to remove in evaluation.csv
Upload table of locations with problematic reports (updated Aug 31st). Issues cited at: 
[https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#retrospective-reporting-of-probable-cases-and-deaths
](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data#retrospective-reporting-of-probable-cases-and-deaths
)
=> Upload table of problematic dates to remove from evaluation.

data-processed/GT-DeepCOVID/metadata-GT-DeepCOVID.txt
Updating metadata for DeepCOVID
- Team name: DeepCOVID
- Model name that is being updated:  DeepCOVID
---
=> Update metadata of DeepCOVID

data-processed/CEID-Walk/metadata-CEID-Walk.txt
- Team name: CEID
- Model name that is being updated:  Walk
---
=> Add 2020-09-13 forecast for CEID-Walk, correct metadata

data-truth/zoltar-truth-data.py
#1162  Description
This is to resolve this [issue](https://github.com/reichlab/covid19-forecast-hub/issues/1403).
=> Issue 1403: Zoltpy's changes to returned date format breaks truth upload

data-truth/zoltar-truth-data.py
- Update Zoltar truth data generation target horizon from 4 to 20.   
Closes #1091
=> Update from 4 wk ahead to 20 wk for zoltar truth generation.

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> 9/21/2020 JHU_IDD forecast update

data-truth/README.md
Added paragraph about weeks removed from evaluation due to reporting errors. 
--
=> add info about weeks removed

visualization/vis-master/src/components/Panels/Choropleth.vue, visualization/vis-master/src/store/actions.js, visualization/vis-master/src/store/data.js
This temporary solution changes the default target shown to Incident Deaths.
=> Resolves #1536

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> update JHU_IDD-CovidSP 2020-09-27

data-processed/JHUAPL-Bucky/metadata-JHUAPL-Bucky.txt
- Team name: JHUAPL
- Model name that is being updated:  Bucky
---
=> JHUAPL-Bucky 2020-09-28 Forecast

travis/upload_zoltar_master.sh
=> Remove daily truth upload to replace with weekly upload

data-truth/zoltar-truth-data.py
Fix the discrepancy in the truth data values for DC as reported in  #1675 (point (5)).
=> Fix DC truth data

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD CovidSP 10/19/2020 forecast update

data-truth/get-truth-data.py, data-truth/truth_utils/_utils.py, data-truth/zoltar-truth-data.py
=> Issue 1800: Refactor truth codes to remove duplicate codes

data-processed/LANL-GrowthRate/metadata-LANL-GrowthRate.txt
Adding 2020-10-29 Forecasts and updating metadata
- Team name:  LANL
- Model name that is being updated:  GrowthRate
=> LANL-GrowthRate 

visualization/scripts/convert_forecasts.py
Resolves #1860 
This should fix the issue of PR and RI data not showing up in the viz.
=> fixed PR and RI not processing correctly.

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD CovidSP forecast update 11/16/2020

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py
- Fix async delete of forecast when it is being updated.
=> Add another condition check to see if the forecast was not already

README.md
Changes CC-BY-4.0 to CC-BY-NC-4.0
Change Facebook AI Research License in main README to match metadata and LICENSE.txt files.  (CC-BY-4.0 -> CC-BY-NC-4.0)
=> Small change to Facebook AI Research license

code/notebooks/remove_nohash_from_zoltar.ipynb, code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py
Resolves #1984 
Just a script I wrote to delete existing forecasts. Shouldn't be needed at this point since Abdul's PR #1986, but want to make sure it's in the hub.
=> added script to remove forecasts that are uploaded to Zoltar but are not in json

data-processed/USC-SI_kJalpha/metadata-USC-SI_kJalpha.txt
Weekly forecast updates.
Meta-description update.
- Team name: USC
- Model name that is being updated:  SI_kJalpha
---
=> USC-SI_kJalpha: Weekly update

data-processed/USC-SI_kJalpha/metadata-USC-SI_kJalpha.txt
We have updated the meta-data file to reflect our data source for hospitalization forecasts.
=> Added hospitalization data source USC-SIkJalpha

data-processed/CU-nochange/metadata-CU-nochange.txt, data-processed/CU-scenario_high/metadata-CU-scenario_high.txt, data-processed/CU-scenario_low/metadata-CU-scenario_low.txt, data-processed/CU-scenario_mid/metadata-CU-scenario_mid.txt, data-processed/CU-select/metadata-CU-select.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> update CU metadata

data-processed/CU-nochange/metadata-CU-nochange.txt, data-processed/CU-scenario_high/metadata-CU-scenario_high.txt, data-processed/CU-scenario_low/metadata-CU-scenario_low.txt, data-processed/CU-scenario_mid/metadata-CU-scenario_mid.txt, data-processed/CU-select/metadata-CU-select.txt
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> CU Dec 10 and update metadata

data-processed/JHUAPL-Bucky/metadata-JHUAPL-Bucky.txt
- Team name: JHUAPL
- Model name that is being updated:  Bucky
---
=> JHUAPL-Bucky 2020-12-14 Forecast and updated metadata

data-truth/nytimes/nytimes.py, travis/update_truth_weekly.sh
Also, enable the NYTimes Github Action.
Closes #2127
=> Update nytimes script to fix error.

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD CovidSP 2020-12-20 update

code/zoltar_scripts/upload_covid19_forecasts_to_zoltar.py
=> Issue 2049

data-processed/COVIDhub-trained_ensemble/metadata-COVIDhub-trained_ensemble.txt
- Team name: COVIDhub
- Model Name: trained_ensemble
- Institution:  COVIDhub
=> 2021-02-01-COVIDhub-trained_ensemble

visualization/vis-master/src/components/Panels/ChartsPanel.vue
- Update text under the `TimeChart` tab in the visualization from 
> `The ensemble forecast combines models unconditional on particular interventions being in place with those conditional on certain social distancing measures continuing. To ensure consistency, only models with 4 week-ahead forecasts ahead are included in the ensemble.`   
to   
> `The ensemble forecast is a multi-model ensemble developed and published weekly in real-time that combines models with varied approaches, data sources, and assumptions.`
=> Update text under `TimeChart`

.github/workflows/model_validation_v2.yml
- Add the new validations workflow.
=> Add new validations flow to PR builds.

data-truth/usafacts/usafacts.py
Fix usafacts column name change since it's breaking weekly truth update
#2881
=> Address usafact column name change stateFIPS to StateFIPS

data-processed/README.md
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Update README.md with policy update

visualization/vis-master/scripts/parse-season.js
Extend x-axis on visualization
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Extend to 24 weeks on x-axis

.github/workflows/active_update_truth_weekly.yml, .github/workflows/deprecated_update_truth_weekly.yml, data-truth/get_visualization_truth_json_from_csv.py
=> Add new GH action that upload unit-tested truth

.github/workflows/deprecated_update_truth_weekly.yml
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Remove redundant nodejs for truth update

.github/workflows/active_update_truth_weekly.yml, .github/workflows/upload_to_zoltar.yml
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Remove some pre-installed software for more space in GitHub Action

data-processed/Geneva-DetGrowth/LICENSE.txt, data-processed/Geneva-DetGrowth/metadata-Geneva-DetGrowth.txt
1. Update metadata including model description, list of contributors, etc. We leave model_abbr unchanged for now. 
2. License our forecasts with CC-BY-4.0.
---
=> Geneva-DetGrowth - Update metadata and LICENSE

data-processed/RobertWalraven-ESG/metadata-RobertWalraven-ESG.txt
Update long description in metafile
- Team name: Robert Walraven
- Model Name: ESG
=> metadata-RobertWalraven-ESG

data-truth/README.md
Update truth readme with new scripts and data details
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Update truth readme with new scripts and data details

code/zoltar_scripts/validated_file_db.json
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> remove entries that didn't get uploaded to re-upload again

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD CovidSP 4/11 forecast update

data-processed/PandemicCentral-COVIDForest/metadata-PandemicCentral-COVIDForest.txt, data-processed/PandemicCentral-USCounty/metadata-PandemicCentral-USCounty.txt
- Team name: Pandemic Central
- Model Name: COVIDForest
- Institution: University of Dallas
We would also like to update the metadata of our old model (model designation should be *'other'*). The new model *COVIDForest* should be the *primary* model from now on.
=> Pandemic Central: Initial Forecasts (2021-04-17)

data-processed/README.md
- Update on the validations section of the README
- Minor update in the text of retractions section.
=> Update README in validations section + retractions

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
Update with 2021-04-25 forecasts. Forecasts are state-level only for this submission.
---
- Team name: JHU IDD
- Model name that is being updated:  COVID Scenario Pipeline
---
=> 2021-04-25 submission

.github/workflows/active_update_truth_weekly.yml
Increase memory used for installing packages in Weekly truth update workflow
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> Increase memory used for installing packages

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> JHU_IDD CovidSP 5/16 forecast update

data-anomalies/plot_data_for_review.Rmd, plot_data_for_review.Rmd
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> data anomalies: add points for negative values and outliers

data-anomalies/plot_data_for_review.Rmd
---
- Team name: 
- Model Name: 
---
- Team name: 
---
=> suppress message output

data-processed/JHU_IDD-CovidSP/metadata-JHU_IDD-CovidSP.txt
=> 7/18 JHU_IDD CovidSP forecast update

code/reports/plot-hospitalizations.R
Add a more informative error msg to plot_hospitalization_forecasts() function if invalid argument is fed into function
=> Added error msg to plot_hospitalization_forecasts() func

code/reports/all-states-weekly-report.Rmd, code/reports/render_reports.R, code/reports/weekly-report.Rmd
added some new features to weekly reports generation:
* Better Zoltar connection mechanism
* Script now makes a new connection to share between all report-generation threads
* autodetection of multi-core environment
* defaults back to non-parallel execution if multi-core not detected
* adds retry mechanism
* retries failed state-level reports once, if fails again will need manual input
=> Revamp: better Zoltar connection mechanism + failure catching

data-processed/GT-DeepCOVID/metadata-GT-DeepCOVID.txt
=> Add citation to DeepCOVID metadata

data-processed/PSI-DRAFT/metadata-PSI-DRAFT.txt
=> PSI-DRAFT meta update

data-processed/CUBoulder-COVIDLSTM/metadata-CUBoulder-COVIDLSTM.txt
=> updated CUBoulder metadata

data-processed/METADATA.md
=> Fix typo in metadata wiki page

data-processed/JBUD-HMXK/2021-11-21-JBUD-HMXK.csv
=> 2021-11-21 - JBUD submission

data-processed/Karlen-pypm/metadata-Karlen-pypm.txt
=> take out duplicate key in metadata-Karlen-pypm.txt

data-processed/JBUD-HMXK/2021-12-19-JBUD-HMXK.csv
=> 2021-12-19 - JBUD submission

data-processed/JBUD-HMXK/2021-12-26-JBUD-HMXK.csv
=> 2021-12-26 - JBUD submission

data-processed/JBUD-HMXK/2022-01-02-JBUD-HMXK.csv
=> 2021-01-02 - JBUD submission

data-processed/UMass-trends_ensemble/metadata-UMass-trends_ensemble.txt
as per recommendation from CDC and CMU collaborators
=> Add secondary model designation for UMass-trends_ensemble

data-processed/JBUD-HMXK/2022-01-09-JBUD-HMXK.csv, data-processed/JBUD-HMXK/2022-01-16-JBUD-HMXK.csv
=> 2021-01-16 - JBUD submission

data-processed/CMU-TimeSeries/metadata-CMU-TimeSeries.txt
This metadata update describes the state hospitalization forecasting system, plus changes made in the past to the state inc death and county inc case forecasters.  As the hospitalization forecaster is still under rapid development, there will likely be additional metadata updates for the following submissions.
=> Update CMU-TimeSeries metadata

data-processed/JBUD-HMXK/2022-01-23-JBUD-HMXK.csv
=> 2021-01-23 - JBUD submission

data-processed/JBUD-HMXK/2022-01-30-JBUD-HMXK.csv
=> 2021-01-30 - JBUD submission

.github/workflows/active_update_truth_weekly.yml
=> add a condition about repo owner

data-processed/Microsoft-DeepSTIA/metadata-Microsoft-DeepSTIA.txt
=> update meta info

data-processed/JBUD-HMXK/2022-02-06-JBUD-HMXK.csv
=> 2021-02-06 - JBUD submission

data-processed/JBUD-HMXK/2022-02-13-JBUD-HMXK.csv
=> 2021-02-13 - JBUD submission

data-processed/JBUD-HMXK/2022-02-20-JBUD-HMXK.csv
=> 2021-02-20 - JBUD submission

data-processed/JBUD-HMXK/2022-02-27-JBUD-HMXK.csv
=> 2021-02-27 - JBUD submission

.github/workflows/validations_v4.yml
=> update validation workflow

data-processed/JBUD-HMXK/2022-03-06-JBUD-HMXK.csv
=> 2022-03-06 - JBUD submission

data-processed/JBUD-HMXK/2022-03-13-JBUD-HMXK.csv
=> 2022-03-13 - JBUD submission

data-processed/COVIDhub_CDC-ensemble/metadata-COVIDhub_CDC-ensemble.txt
=> update year of weighted ensemble in metadata

data-processed/JBUD-HMXK/2022-03-20-JBUD-HMXK.csv
=> 2022-03-20 - JBUD submission

data-processed/JBUD-HMXK/2022-03-27-JBUD-HMXK.csv
=> 2022-03-27 - JBUD submission

.github/workflows/validations_v4.yml
=> add: zoltpy credentials

code/R_scripts/generate_truth_csvs.R
=> Update generate_truth_csvs.R - temporarily remove nyt

data-processed/AIMdyn-SlidingKoopman/2023-01-21-AIMdyn-SlidingKoopman.csv, data-processed/AIMdyn-SlidingKoopman/metadata-AIMdyn-SlidingKoopman.txt
team_name: AIMdyn Inc.
model_name: Sliding Koopman
Adding predictions for 01/21/2023
=> AIMdyn forecasts for 01/21/2023

code/validation/test_formatting.py
Here's an attempted fix to the occasional `upload_to_zoltar.yml` workflow `github.GithubException.RateLimitExceededException` failure. It's difficult to test this fix without deploying to production. This fix worked in [`covid19-forecast-evals/code/get_file_version_version_full.py`](https://github.com/reichlab/covid19-forecast-evals/blob/main/code/get_file_version_version_full.py) , but that was a different application, so our results will vary.
=> attempted fix of "API rate limit exceeded" - sleeps for a minute if up against rate limit

data-processed/AIMdyn-SlidingKoopman/2023-01-28-AIMdyn-SlidingKoopman.csv, data-processed/AIMdyn-SlidingKoopman/2023-01-29-AIMdyn-SlidingKoopman.csv
team_name: AIMdyn Inc.
model_name: Sliding Koopman
Adding predictions for 01/28/2023
=> AIMdyn forecasts for 01/28/2023

data-processed/AIMdyn-SlidingKoopman/2023-02-19-AIMdyn-SlidingKoopman.csv
team_name: AIMdyn Inc.
model_name: Sliding Koopman
Adding predictions for 02/18/2023
=> AIMdyn forecasts for 02/18/2023

code/reports/all-states-weekly-report.Rmd, code/reports/weekly-report.Rmd
=> Remove deaths from weekly reports

data-processed/UT-Osiris/metadata-UT-Osiris.txt
=> Updated Metadata-UT-Osiris

.github/workflows/active_update_truth_weekly.yml, .github/workflows/upload_to_zoltar.yml
=> unschedule routine covid hub actions

.github/workflows/validations_v4.yml
=> Update validations_v4.yml - do not run on PR submission

README.md, data-processed/README.md
=> Add note on submissions

.github/workflows/validations_v4.yml
=> Update validations_v4.yml - run on workflow_dispatch

data-processed/UT-Osiris/metadata-UT-Osiris.txt
=> UT Osiris:  Update metadata-UT-Osiris.txt
